### ISSUE TITLE
Error using `pip install -e setup/ --user` using the fixBroken branch

### ISSUE THREAD

**Issue by aik7** [exalearn/EXARL#256]
```
Building wheels for collected packages: tensorflow-gpu, mpi4py
  Building wheel for tensorflow-gpu (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-y2q1rhfs/tensorflow-gpu_4709154dcd1d4dc99cc2b6abfb8dd840/setup.py", line 37, in <module>
          raise Exception(TF_REMOVAL_WARNING)
      Exception:
      
      =========================================================
      The "tensorflow-gpu" package has been removed!
      
      Please install "tensorflow" instead.
      
      Other than the name, the two packages have been identical
      since TensorFlow 2.1, or roughly since Sep 2019. For more
      information, see: pypi.org/project/tensorflow-gpu
      =========================================================
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tensorflow-gpu
  Running setup.py clean for tensorflow-gpu
  Building wheel for mpi4py (pyproject.toml) ... done
  Created wheel for mpi4py: filename=mpi4py-3.1.4-cp37-cp37m-linux_x86_64.whl size=2676082 sha256=6b62daa202d3944766914c31e845f235b3a756013a6a3cba4a040d3f4f31c177
  Stored in directory: /global/u2/a/aik7/.cache/pip/wheels/87/81/66/c445deac61f7fb9b727c7b87ecc42dba6b948a03674b2fc56d
Successfully built mpi4py
Failed to build tensorflow-gpu
Installing collected packages: pytz, python_version, zipp, tensorflow-gpu, python-dateutil, pyparsing, pillow, packaging, mpi4py, llvmlite, kiwisolver, fonttools, cycler, coverage, pandas, matplotlib, importlib-metadata, numba, exarl
  Running setup.py install for tensorflow-gpu ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for tensorflow-gpu did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-y2q1rhfs/tensorflow-gpu_4709154dcd1d4dc99cc2b6abfb8dd840/setup.py", line 37, in <module>
          raise Exception(TF_REMOVAL_WARNING)
      Exception:
      
      =========================================================
      The "tensorflow-gpu" package has been removed!
      
      Please install "tensorflow" instead.
      
      Other than the name, the two packages have been identical
      since TensorFlow 2.1, or roughly since Sep 2019. For more
      information, see: pypi.org/project/tensorflow-gpu
      =========================================================
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> tensorflow-gpu

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by aik7** [comment]
When I tried to use my old exarl conda environment, I get the following error when I run:
```
python exarl/driver/ --env Pendulum-v0 --n_episodes 50 --n_steps 200 --learner_procs 1 --workflow sync --agent DDPG-v0 --model_type AC
```

```
Traceback (most recent call last):
  File "/global/homes/a/aik7/anaconda3/envs/exarl/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/global/homes/a/aik7/anaconda3/envs/exarl/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "exarl/driver/__main__.py", line 30, in <module>
    exa_learner = exarl.ExaLearner()
  File "/global/u2/a/aik7/EXARL/exarl/base/learner_base.py", line 46, in __init__
    self.agent, self.env, self.workflow = self.make(agent_id, env_id, workflow_id)
  File "/global/u2/a/aik7/EXARL/exarl/base/learner_base.py", line 95, in make
    agent = exarl.agents.make(agent_id, env=env, is_learner=ExaComm.is_learner())
  File "/global/u2/a/aik7/EXARL/exarl/agents/registration.py", line 98, in make
    return registry.make(id, **kwargs)
  File "/global/u2/a/aik7/EXARL/exarl/agents/registration.py", line 58, in make
    agent = spec.make(**kwargs)
  File "/global/u2/a/aik7/EXARL/exarl/agents/registration.py", line 43, in make
    agent = cls(**_kwargs)
  File "/global/u2/a/aik7/EXARL/exarl/agents/agent_vault/ddpg.py", line 75, in __init__
    self.actor.init_model()
  File "/global/u2/a/aik7/EXARL/exarl/agents/models/tf_model.py", line 194, in init_model
    self._compile()
  File "/global/u2/a/aik7/EXARL/exarl/agents/models/tf_model.py", line 146, in _compile
    self._model.compile(loss=self.loss, optimizer=self.optimizer, jit_compile=self.enable_xla)
  File "/global/homes/a/aik7/anaconda3/envs/exarl/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 534, in compile
    self._validate_compile(optimizer, metrics, **kwargs)
  File "/global/homes/a/aik7/anaconda3/envs/exarl/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2520, in _validate_compile
    (invalid_kwargs,))
```

**Comment by aik7** [comment]
I actually tried to do: 

`conda install -c anaconda tensorflow-gpu -y`

as it also stated here, 
https://github.com/exalearn/EXARL/wiki/EXARL-on-Perlmutter

However,  I get `CondaVerificationError`.

**Comment by aik7** [comment]
Fix the conda verification error by  `conda clean --all`
